apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutate-example-admission-controller
webhooks:
  - name: mutating-webhook.openpolicyagent.org
    clientConfig:
      service:
        name: mutate-example
        namespace: demo-mutate
      caBundle: <paste your cabundle>
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    objectSelector:
      matchLabels:
        app: mutate-me
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: Fail