---
apiVersion: v1
kind: Pod
metadata:
  name: mutate-me
  namespace: demo-mutate
  annotations:
    patch1: "yes"
  labels:
    app: mutate-me
spec:
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']